// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB0uR2q8_nfldRT6_yYnqR1m-ZUdqCFbw',
    appId: '1:110737865436:web:e005f7828dc4046edb9219',
    messagingSenderId: '110737865436',
    projectId: 'quran-reportweb',
    authDomain: 'quran-reportweb.firebaseapp.com',
    storageBucket: 'quran-reportweb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs1M0fxMZLh0hL2sLXsSicgHzohHbe344',
    appId: '1:110737865436:android:663df9f99fffbea4db9219',
    messagingSenderId: '110737865436',
    projectId: 'quran-reportweb',
    storageBucket: 'quran-reportweb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp_8BTMyJHbbeHNlrxCcwmYwvevUmEV_I',
    appId: '1:110737865436:ios:418b455f111149c3db9219',
    messagingSenderId: '110737865436',
    projectId: 'quran-reportweb',
    storageBucket: 'quran-reportweb.firebasestorage.app',
    iosBundleId: 'com.example.quranReportParent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp_8BTMyJHbbeHNlrxCcwmYwvevUmEV_I',
    appId: '1:110737865436:ios:418b455f111149c3db9219',
    messagingSenderId: '110737865436',
    projectId: 'quran-reportweb',
    storageBucket: 'quran-reportweb.firebasestorage.app',
    iosBundleId: 'com.example.quranReportParent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB0uR2q8_nfldRT6_yYnqR1m-ZUdqCFbw',
    appId: '1:110737865436:web:05a4896b6498bf1bdb9219',
    messagingSenderId: '110737865436',
    projectId: 'quran-reportweb',
    authDomain: 'quran-reportweb.firebaseapp.com',
    storageBucket: 'quran-reportweb.firebasestorage.app',
  );
}
